name: Create Release and Update Repository

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  release:
    uses: ./.github/workflows/reusable_create_release.yml
    with:
      internal_name: OrchestrionPlugin
      solution_name: Orchestrion
      build_configuration: Release
      personal_plugin_repo: PhibrXIV/DalamudPluginRepo
      personal_plugin_repo_branch: master
      plugin_folder: orchestrion
      project_dir: Orchestrion
      platform: x64
    secrets: inherit
